source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, ‘9.0’
inhibit_all_warnings!

target 'Guardian Forestal' do

  # Pods for Guardian Forestal
  #pod 'SideMenuController'
  pod 'SwiftLocation'
  pod 'MapboxGeocoder.swift', '~> 0.6'

end
